version: '3'

services:
  server_manager:
    image: openjdk:11.0.14.1-jre
    volumes:
      - $PWD/:/usr/local/server-manager
    environment:
      - LC_ALL=C.UTF-8
      - TZ=Asia/Seoul
    restart: always
    network_mode: "host"
    logging:
      driver: "syslog"
    entrypoint: 
        - sh
        - -c 
        - /usr/local/server-manager/start.sh
