version: '3'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:stable-alpine-perl
    environment:
      - LC_ALL=C.UTF-8
      - TZ=Asia/Seoul
    restart: always
    network_mode: "host"
    volumes:
      -  $PWD/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      -  $PWD/nginx/conf.d/:/etc/nginx/conf.d/
      -  $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
      -  $PWD/logs/:/var/log/nginx/
      -  /root/pem/:/root/pem/
      -  /var/www/html/:/var/www/html/
      -  /usr/local/favicon:/usr/local/favicon/
